---
name: Open upstream PR
on:
  push:
    branches:
    - staging
  workflow_dispatch:

jobs:
  pull-request:
    if: github.repository != 'aucloud/vcd-postman-collection'
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.WRITE_PAT }} 
        fetch-depth: 0
    - name: Login to github
      run: |
        echo ${{ secrets.WRITE_PAT }} | gh auth login --hostname github.ss.australiacloud.com.au --with-token --base main --head staging
    - name: gh pr create
      run: |
        gh pr create --title "PR from public github" --body "Please merge me ASAP"
    - name: Cleanup github login
      if: always()
      run: gh auth logout --hostname github.ss.australiacloud.com.au